# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Uploading' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Uploading
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3' 
end
